gtk-rs/gtk4-rs

- Gir.toml
- src/auto/functions.rs
- src/rt.rs
These functions are supposed to be manual anyway, so we remove them from gir.
Fixes #14
> Don't assert initialized for is_initialized

- .github/workflows/CI.yml
- Cargo.toml
- examples/Cargo.toml
- examples/src/bin/basic.rs
Setup the necessary stuff to include more examples in the future
> examples: add a basic one

- gdk4-x11/Cargo.toml
- gdk4-x11/src/lib.rs
- gdk4-x11/sys/Cargo.toml
- gdk4-x11/sys/tests/abi.rs
noticed that in https://gtk-rs.org/gtk4-rs/gdk_x11_sys/index.html
> gdkx11: fix crate name

- generator.py
Apply changes from https://github.com/gtk-rs/gtk-rs/pull/170.
> generator: Convert to pathlib, fix wrong path passed to various executables and remove python2 code

- generator.py
Follows https://github.com/gtk-rs/gtk-rs/pull/176
> generator: Autoformat and normalize quotation with `black`

- gtk4/src/subclass/widget.rs
The way we previously handled measure didn't work
with the way measure actually works. It caused
a critical issue as widget subclasses were using
a measure func that did not behave properly.
This would lead to a crash.
With these changes we now handle measure in a simple
"default" way.
> subclass/widget: Rework the default measure() vfunc

- gtk4/Gir.toml
- gtk4/src/auto/recent_info.rs
- gtk4/src/auto/recent_manager.rs
- gtk4/src/auto/scale_button.rs
- gtk4/src/auto/search_bar.rs
- gtk4/src/auto/search_entry.rs
- gtk4/src/auto/selection_model.rs
- gtk4/src/auto/settings.rs
- gtk4/src/auto/shortcut_trigger.rs
- gtk4/src/auto/signal_action.rs
- gtk4/src/auto/single_selection.rs
- gtk4/src/auto/stack.rs
- gtk4/src/auto/stack_page.rs
- gtk4/src/auto/string_filter.rs
- gtk4/src/auto/style_context.rs
- gtk4/src/auto/text_iter.rs
- gtk4/src/auto/text_view.rs
- gtk4/src/auto/tree_model.rs
- gtk4/src/auto/tree_view.rs
- gtk4/src/auto/widget.rs
- gtk4/src/auto/window.rs
> gtk: nullability trust part 3

- gtk4/src/subclass/filter.rs
- gtk4/src/subclass/layout_manager.rs
- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/scrollable.rs
- gtk4/src/subclass/sorter.rs
- Add `GtkLayoutManager` 
- Add `GtkScrollable`
- Add `GtkFilter`
- Add `GtkSorter`
Part of #56
> Subclassing round 4

- gtk4/src/subclass/actionable.rs
- gtk4/src/subclass/editable.rs
- gtk4/src/subclass/media_file.rs
- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/recent_manager.rs
Add 
- `GtkRecentManager`
- `GtkMediaFile`
- `GtkActionable`
- `GtkEditable`
part of #56
> Subclassing part 3

- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/text_buffer.rs
- gtk4/src/subclass/text_view.rs
> gtk: add TextBuffer/TextView subclassing support

- gtk4/src/subclass/frame.rs
- gtk4/src/subclass/gl_area.rs
- gtk4/src/subclass/media_file.rs
- gtk4/src/subclass/media_stream.rs
- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/shortcut_manager.rs
Add subclassing support of the following types:
- GtkMediaStream
- GtkShortcutManager
- GtkFrame
- GtkGLArea
part of #56
> gtk: subclassing round 7

- gtk4/src/subclass/widget.rs
- compute_expand is optional and a parent class might not be implementing it
- compute_expand might return an uninitialized pointer for hexpand/vexpand
in case the vexpand-set/hexpand-set were set to False
Fixes #95
> gtk: fix compute_expand implementation

- gtk4/Gir.toml
- gtk4/src/auto/builder.rs
- gtk4/src/auto/calendar.rs
- gtk4/src/auto/color_button.rs
- gtk4/src/auto/column_view.rs
- gtk4/src/auto/combo_box.rs
- gtk4/src/auto/constraint_layout.rs
> Fix some nullable return annotations 2

- gtk4/src/subclass/widget.rs
Useful for subclassing Widget.
> Add 2 widget class methods

- gtk4/src/subclass/widget.rs
> gtk: add more WidgetClass methods

- examples/src/bin/widget_subclass.rs
Requires https://github.com/gtk-rs/gtk-rs/pull/214
> examples: Move unparent to dispose()

- examples/src/bin/composite_template.rs
- gtk4/src/prelude.rs
- gtk4/src/widget.rs
Requires https://github.com/gtk-rs/gtk-rs/pull/216
> Hook up gtk_widget_init_template() into InitializingObject

- gdk4-wayland/Cargo.toml
- gdk4-wayland/build.rs
- gdk4-x11/Cargo.toml
- gdk4-x11/build.rs
- gdk4/build.rs
- gsk4/build.rs
- gtk4/build.rs
> docs features

- examples/Cargo.toml
- examples/src/bin/basic.rs
- examples/src/bin/builder_basics.rs
- examples/src/bin/builders.rs
- examples/src/bin/clock.rs
- examples/src/bin/composite_template.rs
- examples/src/bin/css.rs
- examples/src/bin/entry_completion.rs
- examples/src/bin/widget_subclass.rs
- gdk4-x11/src/lib.rs
- gdk4/src/lib.rs
- gdk4/src/prelude.rs
- gsk4/src/lib.rs
- gsk4/src/prelude.rs
- gtk4/src/lib.rs
- gtk4/src/prelude.rs
> Rexport dependencies from gtk

- gtk4/Gir.toml
- gtk4/src/auto/drawing_area.rs
- gtk4/src/auto/list_box.rs
- gtk4/src/drawing_area.rs
- gtk4/src/flow_box.rs
- gtk4/src/lib.rs
- gtk4/src/list_box.rs
- gtk4/src/prelude.rs
> simpler callbacks: avoid Option<Box<Q>>

- examples/Cargo.toml
- examples/src/bin/custom_paintable.rs
- gdk4/src/lib.rs
- gdk4/src/rgba.rs
- gdk4/src/subclass/mod.rs
- gdk4/src/subclass/paintable.rs
- gtk4/src/subclass/mod.rs
> gdk: add Paintable subclassing support

- gdk4-wayland/sys/Gir.toml
- gdk4-x11/sys/Gir.toml
- gdk4/sys/Gir.toml
- gsk4/sys/Gir.toml
- gtk4/sys/Gir.toml
This is now checked by `checker` so unless this PR is merged, CI will fail. ;)
> Fix weird indents in toml files

- examples/Cargo.toml
- examples/src/bin/orientable_subclass.rs
- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/orientable.rs
Fixes: https://github.com/gtk-rs/gtk4-rs/issues/147
> gtk: Add Orientable subclassing support

- gtk4/Gir.toml
- gtk4/src/application.rs
- gtk4/src/auto/application.rs
- gtk4/src/auto/mod.rs
- gtk4/src/lib.rs
> gtk: generate ApplicationBuilder manually

- gtk4/src/subclass/layout_manager.rs
> gtk: allow setting layout_child_type on GtkLayoutManager

- examples/Cargo.toml
- examples/src/bin/dialog.rs
- gtk4/Cargo.toml
- gtk4/src/dialog.rs
> Add Dialog::run_future()

- examples/Cargo.toml
Or is there a reason to use `autobins = false`?
> examples: Use autobins

- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/print_operation.rs
- gtk4/src/subclass/print_operation_preview.rs
- gtk4/src/subclass/tree_view.rs
Adds subclassing support for 
- GtkTreeView
- GtkPrintOperation
- GtkPrintOperationPreview
Part of #56
> Subclassing round 9

- gtk4/src/subclass/color_chooser.rs
- gtk4/src/subclass/combo_box.rs
- gtk4/src/subclass/entry_buffer.rs
- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/range.rs
- gtk4/src/subclass/scale.rs
- gtk4/src/subclass/scale_button.rs
Add subclassing support of  the following types:
- GtkColorChooser
- GtkComboBox
- GtkEntryBuffer
- GtkRange
- GtkScale
- GtkScaleButton
Part of #56
> gtk: subclassing round 6

- examples/src/bin/composite_template.rs
- examples/src/bin/video_player.rs
- gtk4-macros/src/attribute_parser.rs
- gtk4-macros/src/composite_template_derive.rs
- gtk4-macros/src/lib.rs
- gtk4/src/subclass/widget.rs
The source can be a file, a resource, or a string.
> Specify template as an attribute of CompositeTemplate

- gtk4/Gir.toml
- gtk4/src/auto/editable.rs
- gtk4/src/auto/widget.rs
- gtk4/src/widget.rs
> Some small fixes

- gtk4/src/subclass/im_context.rs
- gtk4/src/subclass/mod.rs
> gtk: add IMContext subclassing support

- gdk4/Gir.toml
- gdk4/src/auto/gl_texture.rs
- gdk4/src/gl_texture.rs
- gdk4/src/lib.rs
Fixes: https://github.com/gtk-rs/gtk-rs/issues/295
> gdk: bind gdk_gl_texture_new

- .github/workflows/image.yml
- Dockerfile
Builds and publish a docker image that will be used in the future for the docs
> CI: build and publish a docker image

- examples/src/bin/composite_template.rs
- examples/src/bin/custom_paintable.rs
- examples/src/bin/orientable_subclass.rs
- examples/src/bin/video_player.rs
- examples/src/bin/widget_subclass.rs
- gtk4-macros/src/lib.rs
Depends on https://github.com/gtk-rs/gtk-rs/pull/335
> update per glib::object_subclass changes

- gdk4/src/subclass/paintable.rs
- gtk4/src/subclass/accessible.rs
- gtk4/src/subclass/actionable.rs
- gtk4/src/subclass/app_chooser.rs
- gtk4/src/subclass/builder_scope.rs
- gtk4/src/subclass/color_chooser.rs
- gtk4/src/subclass/constraint_target.rs
- gtk4/src/subclass/editable.rs
- gtk4/src/subclass/file_chooser.rs
- gtk4/src/subclass/native.rs
- gtk4/src/subclass/orientable.rs
- gtk4/src/subclass/print_operation_preview.rs
- gtk4/src/subclass/root.rs
- gtk4/src/subclass/scrollable.rs
- gtk4/src/subclass/selection_model.rs
- gtk4/src/subclass/shortcut_manager.rs
- gtk4/src/subclass/tree_drag_dest.rs
- gtk4/src/subclass/tree_drag_source.rs
Details at https://github.com/gtk-rs/gtk-rs/pull/352
> subclassing: interfaces are now distinct from objects

- .github/workflows/image.yml
- Dockerfile
> dockerfile: bump to gtk 4.1.2

- gtk4/src/subclass/fixed.rs
- gtk4/src/subclass/grid.rs
- gtk4/src/subclass/layout_child.rs
- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/text_child_anchor.rs
- gtk4/src/subclass/text_mark.rs
- gtk4/src/subclass/text_tag.rs
- gtk4/src/subclass/window_group.rs
> gtk: add subclassing support for more types

- examples/src/bin/application_subclass.rs
- gtk4/src/subclass/application.rs
Yes, that's all the change that was necessary to fix it.
> gtk: Application subclass initialization fix

- gdk4/src/prelude.rs
> gdk: add ToplevelExtManual to prelude

- gtk4/Cargo.toml
- gtk4/README.md
- gtk4/src/lib.rs
> gtk: add features to re-export gdk-x11 & gdk-wayland

- .github/workflows/docs.yml
> CI: properly link to external docs

- examples/entry_completion/main.rs
- gtk4/src/list_store.rs
- gtk4/src/tree_store.rs
> Backport gtk-rs/gtk-rs#312

- gtk4/Gir.toml
> get_widget_name return annotation fixed upstream

- gdk4-x11/Gir.toml
- gdk4-x11/src/lib.rs
- gdk4-x11/src/x11_display.rs
> gdk-x11: manual impl get_xdisplay and get_xsreen

- book/src/gobject_signals.md
- book/src/introduction.md
- book/src/settings.md
- book/src/widgets.md
This is now possible thanks to #275
> Use relative paths to gtk4-rs docs

- gtk4/src/subclass/builder_scope.rs
Once https://github.com/gtk-rs/gtk-rs/pull/428 is merged.
This was the only occurrence I found
> Use Error::into_raw()

- gtk4/Gir.toml
- gtk4/src/auto/check_button.rs
- gtk4/src/auto/expander.rs
- gtk4/src/auto/label.rs
- gtk4/src/auto/link_button.rs
Gtk4 side of https://github.com/gtk-rs/gtk-rs/issues/133
> Take str for with_label and with_mnemonic constructors.

- gtk4/src/lib.rs
Based on gtk-rs/gtk-rs#431
Closes #255
> [docs] Adds an introduction for the gtk4 crate

- README.md
- gdk4-wayland/README.md
- gdk4-x11/README.md
- gdk4/README.md
- gsk4/README.md
- gtk4-macros/README.md
- gtk4/README.md
I've noticed that we don't refer to the examples anywhere yet.
Not sure if this is the best place though.
> Add examples to README

- gtk4/Gir.toml
- gtk4/src/assistant.rs
- gtk4/src/auto/assistant.rs
- gtk4/src/auto/callback_action.rs
- gtk4/src/auto/cell_layout.rs
- gtk4/src/auto/combo_box.rs
- gtk4/src/auto/flow_box.rs
- gtk4/src/auto/font_chooser.rs
- gtk4/src/auto/list_box.rs
- gtk4/src/auto/map_list_model.rs
- gtk4/src/auto/menu_button.rs
- gtk4/src/auto/scale.rs
- gtk4/src/auto/tree_selection.rs
- gtk4/src/auto/tree_view.rs
- gtk4/src/auto/tree_view_column.rs
- gtk4/src/cell_layout.rs
- gtk4/src/combo_box.rs
- gtk4/src/flow_box.rs
- gtk4/src/font_chooser.rs
- gtk4/src/lib.rs
- gtk4/src/list_box.rs
- gtk4/src/map_list_model.rs
- gtk4/src/menu_button.rs
- gtk4/src/prelude.rs
- gtk4/src/scale.rs
- gtk4/src/tree_selection.rs
- gtk4/src/tree_view.rs
- gtk4/src/tree_view_column.rs
Fixes #294 
There's a very weird one, [`gtk::MapListModel::new`](https://docs.gtk.org/gtk4/ctor.MapListModel.new.html), I ended up adding a new method there named `MapListModel::without_map_func`. Better name suggestions are very much welcome!
> no more boxes

- .github/workflows/book.yml
> CI: run clippy on book listings

- README.md
> readme: include a note about the other libs part of the ecosystem

- gtk4/src/lib.rs
> Remove 'work in progress' statement

- gdk4-wayland/Cargo.toml
- gdk4-wayland/sys/Cargo.toml
- gdk4-x11/Cargo.toml
- gdk4-x11/sys/Cargo.toml
- gdk4/Cargo.toml
- gdk4/sys/Cargo.toml
- gsk4/Cargo.toml
- gsk4/sys/Cargo.toml
- gtk4-macros/Cargo.toml
- gtk4/Cargo.toml
- gtk4/sys/Cargo.toml
> misc: update Cargo.toml

- gtk4/src/subclass/widget.rs
Depends on #251 being merged first
As those widget_class methods are mostly wrappers around gtk::Shortcut and the C ones not being bindings friendly, I decided to rewrote them instead. 
Part of #111
> more widget class methods

- .gitignore
- book/listings/Cargo.toml
- book/listings/gobject_properties/4/custom_button/imp.rs
- book/listings/gobject_signals/2/main.rs
- book/listings/gobject_signals/3/custom_button/imp.rs
- book/listings/gobject_signals/3/main.rs
- book/listings/gobject_signals/4/custom_button/imp.rs
- book/listings/gobject_signals/4/custom_button/mod.rs
- book/listings/gobject_signals/4/main.rs
- book/src/gobject_properties.md
- book/src/gobject_signals.md
> Address Sebastian's signal comments

- gtk4/src/subclass/widget.rs
Tried it on the video player example with
```rust
for widget_action in klass.query_action() {
println!("{:#?}", widget_action);
}
```
Output:
```rust
WidgetAction {
owner: VideoPlayerWindow,
name: "win.open",
parameter_type: None,
property_name: None,
}
WidgetAction {
owner: GtkWindow,
name: "window.close",
parameter_type: None,
property_name: None,
}
WidgetAction {
owner: GtkWindow,
name: "window.toggle-maximized",
parameter_type: None,
property_name: None,
}
WidgetAction {
owner: GtkWindow,
name: "window.minimize",
parameter_type: None,
property_name: None,
}
WidgetAction {
owner: GtkWindow,
name: "default.activate",
parameter_type: None,
property_name: None,
}
```
seems to be working just fine. 
Part of #111
> gtk: bind WidgetClass::query_action

- book/listings/gobject_values/1/main.rs
- book/src/gobject_values.md
While the listings already build, the book itself had to be adapted.
> Accomodate changes in glib::Value

- gtk4/src/expression.rs
Instead of taking the value_type as param, derive it directly from the closure
> gtk: make ClosureExpression's api a bit nicer

- book/listings/gobject_properties/4/custom_button/mod.rs
- book/listings/gobject_signals/3/custom_button/mod.rs
- book/listings/gobject_signals/4/custom_button/mod.rs
- book/listings/gobject_subclassing/1/custom_button/mod.rs
- book/listings/gobject_subclassing/2/custom_button/mod.rs
- gdk4/src/keymap_key.rs
- gdk4/src/keys.rs
- gdk4/src/rectangle.rs
- gdk4/src/rgba.rs
- gdk4/src/time_coord.rs
- gsk4/src/rounded_rect.rs
- gtk4/src/border.rs
- gtk4/src/css_location.rs
- gtk4/src/expression.rs
- gtk4/src/tree_sortable.rs
> use Self where appropriate part 2

- gtk4/src/subclass/font_chooser.rs
- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/tree_model_filter.rs
split out of #169 as the tree model stuff needs more thinking
part of #56
> gtk: add FontChooser/TreeModelFilter subclassing support

- gtk4/src/subclass/cell_area.rs
- gtk4/src/subclass/cell_area_context.rs
- gtk4/src/subclass/cell_editable.rs
- gtk4/src/subclass/cell_layout.rs
- gtk4/src/subclass/mod.rs
Part of #56 
- GtkCellArea
- GtkCellAreaContext
- GtkCellEditable
- GtkCellLayout
It still needs some cleanup but should be ready for an initial review :)
> Subclassing round 11

- gtk4/Gir.toml
- gtk4/src/builder.rs
- gtk4/src/prelude.rs
> gtk: Builder is final

- gdk4/Cargo.toml
- gsk4/Cargo.toml
- gtk4/Cargo.toml
The minimum supported version in gtk-rs is 1.14
> Update cairo-rs dependency

- gtk4/Cargo.toml
- gtk4/README.md
- gtk4/src/lib.rs
> misc: drop x11/wayland features from gtk4 crate

- gtk4/Gir.toml
- gtk4/src/lib.rs
- gtk4/src/native_dialog.rs
- gtk4/src/prelude.rs
> gtk: Add run_future() for native dialogs

- gtk4/Gir.toml
- gtk4/src/auto/search_bar.rs
> gtk: drop duplicate getter/setters on SearchBar

- gtk4/src/functions.rs
> gtk: make show_about_dialog's behaviour more like the upstream one

- gtk4/Gir.toml
- gtk4/src/auto/constraint_layout.rs
- gtk4/src/constraint_layout.rs
- gtk4/src/lib.rs
Fixes #190
Depends on https://github.com/gtk-rs/gtk-rs-core/pull/63
> gtk: manually bind ConstraintLayout::add_constraints_from_description

- .github/ISSUE_TEMPLATE/asking-for-help.md
Doing the same as https://github.com/gtk-rs/gtk3-rs/pull/533.
> Update issue templates

- book/src/introduction.md
> book: Upgrade license to Creative Commons Attribution 4.0

- examples/dialog/main.rs
> examples: use builder pattern in dialog example

- gdk4/src/keymap_key.rs
- gdk4/src/rectangle.rs
- gdk4/src/rgba.rs
- gsk4/src/color_stop.rs
- gsk4/src/parse_location.rs
- gsk4/src/rounded_rect.rs
- gtk4/src/bitset_iter.rs
- gtk4/src/css_location.rs
- gtk4/src/flags.rs
- gtk4/src/pad_action_entry.rs
- gtk4/src/page_range.rs
- gtk4/src/recent_data.rs
- gtk4/src/requisition.rs
the rest should be handled by gir once glib-wrapper can do that for us
> misc: add doc aliases on manual types

- gtk4/src/subclass/adjustment.rs
- gtk4/src/subclass/builder_scope.rs
- gtk4/src/subclass/cell_area.rs
- gtk4/src/subclass/cell_area_context.rs
- gtk4/src/subclass/cell_editable.rs
- gtk4/src/subclass/cell_layout.rs
- gtk4/src/subclass/cell_renderer.rs
- gtk4/src/subclass/color_chooser.rs
- gtk4/src/subclass/constraint_target.rs
- gtk4/src/subclass/entry_buffer.rs
- gtk4/src/subclass/filter.rs
- gtk4/src/subclass/font_chooser.rs
- gtk4/src/subclass/im_context.rs
- gtk4/src/subclass/layout_child.rs
- gtk4/src/subclass/layout_manager.rs
- gtk4/src/subclass/media_stream.rs
- gtk4/src/subclass/native_dialog.rs
- gtk4/src/subclass/orientable.rs
- gtk4/src/subclass/print_operation_preview.rs
- gtk4/src/subclass/recent_manager.rs
- gtk4/src/subclass/scrollable.rs
- gtk4/src/subclass/selection_model.rs
- gtk4/src/subclass/shortcut_manager.rs
- gtk4/src/subclass/sorter.rs
- gtk4/src/subclass/style_context.rs
- gtk4/src/subclass/text_buffer.rs
- gtk4/src/subclass/tree_drag_dest.rs
- gtk4/src/subclass/tree_drag_source.rs
- gtk4/src/subclass/tree_model_filter.rs
- gtk4/src/subclass/widget.rs
> gtk: panic if gtk wasn't init at class_init/interface_init

- gdk4-wayland/src/lib.rs
- gdk4-x11/src/lib.rs
- gdk4/src/lib.rs
- gsk4/src/lib.rs
- gtk4-macros/src/lib.rs
- gtk4/src/rt.rs
> Add an intro to all crates

- gdk4-wayland/src/lib.rs
- gdk4-x11/src/lib.rs
- gdk4/src/lib.rs
- gsk4/src/lib.rs
- gtk4-macros/src/lib.rs
> Add project logo to docs

- .github/workflows/docs.yml
otherwise the index page's logo is not replaced
> docs: replace rust-logo with gtk-rs logo on the CI stage

- Dockerfile
it would be used by the docs job
> image: install wget as well

- book/listings/gobject_values/1/main.rs
- book/src/gobject_properties.md
- book/src/gobject_signals.md
While reading the GObject Concepts chapter of the book I found there where a few things to improve so I thought I might just open a pull request.
There are just a bunch of minor improvements and a fix for comments in a listing.
Btw. thanks for the book, it's awesome for understanding GTK and glib at a deeper level. I really learned a lot :)
> A few miscellaneous book improvements

- gtk4/Gir.toml
- gtk4/src/auto/builder_list_item_factory.rs
- gtk4/src/auto/list_item.rs
- gtk4/src/auto/mod.rs
> gtk: don't generate a builder for ListItem/BuilderListItemFactory

- gtk4/Gir.toml
- gtk4/src/auto/cell_view.rs
- gtk4/src/auto/functions.rs
- gtk4/src/auto/tree_drag_dest.rs
- gtk4/src/auto/tree_drag_source.rs
> gtk: TreePath fixes

- book/listings/gobject_memory_management/1/main.rs
- book/listings/gobject_memory_management/2/main.rs
- book/listings/gobject_memory_management/3/main.rs
- book/listings/gobject_memory_management/4/main.rs
- book/listings/gobject_properties/1/main.rs
- book/listings/gobject_properties/2/main.rs
- book/listings/gobject_properties/3/main.rs
- book/listings/gobject_properties/4/main.rs
- book/listings/gobject_signals/1/main.rs
- book/listings/gobject_signals/2/main.rs
- book/listings/gobject_signals/3/main.rs
- book/listings/gobject_subclassing/1/main.rs
- book/listings/gobject_subclassing/2/main.rs
- book/listings/hello_world/2/main.rs
- book/listings/hello_world/3/main.rs
- book/listings/lists/1/main.rs
- book/listings/lists/2/main.rs
- book/listings/lists/3/main.rs
- book/listings/lists/4/main.rs
- book/listings/lists/5/main.rs
- book/listings/main_event_loop/1/main.rs
- book/listings/main_event_loop/2/main.rs
- book/listings/main_event_loop/3/main.rs
- book/listings/main_event_loop/4/main.rs
- book/listings/main_event_loop/5/main.rs
- book/listings/saving_window_state/1/main.rs
- book/listings/settings/1/main.rs
- book/listings/settings/2/main.rs
- book/listings/widgets/1/main.rs
- book/listings/widgets/2/main.rs
Also a few smaller rearrangements
> book: Rename `application` to `app` for consistency

- book/src/SUMMARY.md
- book/src/resources.md
> book: Fix resources link

- gdk4/Gir.toml
- gdk4/src/auto/drop.rs
- gdk4/src/drop.rs
Those are needed before releasing 0.2
> Drop api fixes

- book/listings/lists/2/integer_object/imp.rs
- book/src/lists.md
One user got confused that imp.rs was not mentioned anymore
> Clarify list example

- gtk4/src/rt.rs
> Acquire and leak main context in gtk::init()

- book/listings/saving_window_state/1/custom_window/mod.rs
I believe "Get" and "Set" was mixed up in the comments explaining this code
> Fixed comments

- book/listings/gobject_properties/4/custom_button/mod.rs
- book/listings/gobject_signals/3/custom_button/mod.rs
- book/listings/gobject_subclassing/1/custom_button/mod.rs
- book/listings/gobject_subclassing/2/custom_button/mod.rs
- book/listings/interface_builder/2/window/mod.rs
- book/listings/saving_window_state/1/custom_window/mod.rs
- book/listings/todo_app/1/window/mod.rs
- book/src/gobject_properties.md
- book/src/gobject_subclassing.md
> Book: fix some problems with subclassing

- book/listings/todo_app/1/todo_row/todo_row.ui
- book/listings/todo_app/2/todo_row/todo_row.ui
altered the second "margin-start" to "margin-end" for both objects
(this is my first contribution ever ... I don't know anything about the process. Hope it's okay what I've done)
> property name "margin-end" set

- book/listings/gobject_memory_management/4/main.rs
- book/src/gobject_memory_management.md
The explanation did not make sense anymore after a merged PR
> book: Fix explanation in gobject memory management

- book/listings/todo_app/1/window/window.ui
- book/listings/todo_app/2/main.rs
- book/listings/todo_app/2/window/shortcuts.ui
- book/listings/todo_app/2/window/window.ui
- Use general syntax to refer to action targets
- Expand scrolled window
> book: Improve todo_app listing

- examples/css/style.css
> add bracket

- book/listings/todo_app/1/main.rs
- book/listings/todo_app/2/main.rs
- book/listings/todo_app/2/org.gtk-rs.Todo.gschema.xml
- book/listings/todo_app/2/utils.rs
- book/listings/todo_app/2/window/imp.rs
- book/src/gobject_memory_management.md
- book/src/main_event_loop.md
- book/src/saving_window_state.md
- book/src/settings.md
> book: Finish up remainder of app-id

- book/listings/actions/3/main.rs
Fixes https://github.com/gtk-rs/gtk4-rs/issues/604
> Fix action name in book listing

- book/listings/list_widgets/2/main.rs
- book/listings/list_widgets/3/main.rs
- book/listings/list_widgets/4/main.rs
- book/listings/list_widgets/5/main.rs
- book/listings/todo_app/2/window/mod.rs
- book/listings/todo_app/3/window/mod.rs
Takes advantage of
https://github.com/gtk-rs/gtk-rs-core/commit/781c5d7f36c8583c4ebb1335d2a18eac558dfc1a
> book: Simplify `splice` usage

- book/listings/todo_app/2/todo_object/mod.rs
- book/listings/todo_app/2/utils.rs
- book/listings/todo_app/3/utils.rs
- book/src/todo_app_2.md
- A snippet was not shown
- Use data instead of config path
> Fix todo_app_2 chapter

- Cargo.toml
> Add `default-members` to `Cargo.toml`

- book/src/SUMMARY.md
> book: Fix book link

- gtk4/src/closure_expression.rs
I'm not sure if I did it correctly
> Use impl IntoIterator<Item = Expression> in ClosureExpression params

- gtk4/src/closure_expression.rs
Follow up for https://github.com/gtk-rs/gtk4-rs/pull/703
> Allow slices on ClosureExpression's params

- book/listings/list_widgets/2/integer_object/imp.rs
- book/listings/list_widgets/3/integer_object/imp.rs
- book/listings/list_widgets/4/integer_object/imp.rs
- book/listings/list_widgets/5/integer_object/imp.rs
- book/listings/todo_app/1/todo_object/imp.rs
- book/listings/todo_app/1/todo_row/mod.rs
- book/listings/todo_app/2/todo_object/imp.rs
- book/listings/todo_app/2/todo_row/mod.rs
- book/listings/todo_app/3/todo_object/imp.rs
- book/listings/todo_app/3/todo_row/mod.rs
- examples/custom_paintable/custom_paintable/imp.rs
- examples/expressions/metadata/imp.rs
- examples/expressions/note/imp.rs
cc @Hofer-Julian as it modifies the book snippets
> Update per gtk-rs-core simplifications

- gtk4/src/expression.rs
Doesn't need anymore since https://github.com/gtk-rs/gtk4-rs/commit/8218d1d4e8d5d6723c8bb602ff0a0d6497bfebdd
> Remove unnecessary clone

- book/listings/list_widgets/4/main.rs
- book/listings/list_widgets/5/main.rs
- book/listings/list_widgets/6/main.rs
- book/src/list_widgets.md
> book: Use the new expressions API

- gdk4/src/content_formats.rs
- gdk4/src/rgba.rs
- gtk4/src/bookmark_list.rs
- gtk4/src/border.rs
- gtk4/src/directory_list.rs
> Add setters to RGBA & missing builder methods

- gtk4/src/functions.rs
Explanations provided by @sdroege are [here](https://github.com/gtk-rs/gtk3-rs/pull/672#discussion_r749202925).
> Reduce number of allocations in accelerator_parse_with_keycode

- gtk4/src/rt.rs
> gtk: backport macos fix for the main thread

- book/listings/gobject_properties/4/custom_button/imp.rs
- book/listings/gobject_signals/3/custom_button/imp.rs
- book/listings/list_widgets/2/integer_object/imp.rs
- book/listings/list_widgets/3/integer_object/imp.rs
- book/listings/list_widgets/4/integer_object/imp.rs
- book/listings/list_widgets/5/integer_object/imp.rs
- book/listings/todo_app/1/todo_object/imp.rs
- book/listings/todo_app/2/todo_object/imp.rs
- book/listings/todo_app/3/todo_object/imp.rs
- examples/custom_editable/custom_editable/imp.rs
- examples/custom_editable/custom_tag/imp.rs
- examples/custom_layout_manager/custom_layout_child/imp.rs
- examples/custom_orientable/custom_orientable/imp.rs
- examples/expressions/metadata/imp.rs
- examples/expressions/note/imp.rs
- gtk4/src/lib.rs
- gtk4/src/param_spec_expression.rs
- gtk4/src/prelude.rs
See https://github.com/gtk-rs/gtk-rs-core/pull/384
> Update for glib constructor renames

- examples/virtual_methods/base_button/imp.rs
- examples/virtual_methods/base_button/mod.rs
Casting a `&glib::Object` to an instance struct only works if all
private types are zero-sized. Instead of that we can directly get the
subclass implementation struct with safe code from the object reference.
Also various functions were marked as `unsafe` although not actually needed.
----
CC @Cogitri
> examples: Fix up virtual methods example

- gtk4/Gir.toml
- gtk4/src/auto/combo_box.rs
- gtk4/src/auto/tree_selection.rs
- gtk4/src/auto/tree_view.rs
Not sure if they are worth it but those are part of the very few remaining "not generated" functions
> gtk: manually implement callback getters

- gtk4/Gir.toml
- gtk4/src/auto/text_buffer.rs
- gtk4/src/text_buffer.rs
> gtk: re-implement missing TextBuffer functions

- book/listings/gobject_memory_management/4/main.rs
- book/src/gobject_memory_management.md
Signed-off-by: Hanif Ariffin <hanif.ariffin.4326@gmail.com>
> Fix code snippets and some formatting in gobject_memory_management

- gtk4/Gir.toml
- gtk4/src/auto/widget.rs
Fixes #762
Haven't locally tested it yet
> Gir.toml: Add bool_return_is_error on activate_action_variant

- .github/workflows/CI.yml
- gdk4/src/functions.rs
> docs: test missing rustdoc-stripper-ignore-next on CI

- gtk4/src/actionable.rs
> gtk: use ToVariant for Actionable::set_action_target

- gdk4/Gir.toml
- gdk4/src/auto/gl_texture.rs
- gdk4/src/auto/memory_texture.rs
- gdk4/src/auto/texture.rs
- gdk4/src/lib.rs
From the docs they are immutable and safe
https://docs.gtk.org/gdk4/class.Texture.html
See https://gitlab.gnome.org/GNOME/gtk/-/commit/6785461c2651ad502f46521536619ea77f04dd63
> gdk: Implement Send+Sync for texture

- .github/workflows/windows-msvc.yml
> CI: add Windows MSCV

- gdk4-wayland/Cargo.toml
- gdk4-wayland/sys/Cargo.toml
- gdk4-x11/Cargo.toml
- gdk4-x11/sys/Cargo.toml
- gdk4/Cargo.toml
- gdk4/sys/Cargo.toml
- gsk4/Cargo.toml
- gsk4/sys/Cargo.toml
- gtk4-macros/Cargo.toml
- gtk4/Cargo.toml
- gtk4/sys/Cargo.toml
It'll fail until https://github.com/gtk-rs/gtk-rs-core/pull/473 is merged.
> Update crate versions

- book/src/installation_linux.md
- book/src/project_setup.md
- book/src/settings.md
@bilelmoussaoui @sdroege 
Fixes #827
> book: Remove all mentions of meson and flatpak

- book/listings/saving_window_state/1/custom_window/imp.rs
- book/listings/settings/1/main.rs
- book/src/actions.md
- book/src/css.md
- book/src/gobject_memory_management.md
- book/src/gobject_properties.md
- book/src/gobject_signals.md
- book/src/gobject_subclassing.md
- book/src/gobject_values.md
- book/src/hello_world.md
- book/src/interface_builder.md
- book/src/introduction.md
- book/src/list_widgets.md
- book/src/main_event_loop.md
- book/src/project_setup.md
- book/src/saving_window_state.md
- book/src/settings.md
- book/src/todo_app_1.md
- book/src/todo_app_2.md
- book/src/widgets.md
@BrainBlasted & @YaLTeR since you complained about this.
> book: Add contractions

- book/src/hello_world.md
> Add a sentence

- .github/workflows/image.yml
- Dockerfile
only publish once it is merged
> image: build on PR as well

- gtk4-macros/src/lib.rs
As per discussion in https://github.com/gtk-rs/gtk-rs-core/pull/434
> gtk4-macros: Use relative doc links for glib/gtk items

- .github/workflows/CI.yml
- README.md
- gdk4-wayland/Cargo.toml
- gdk4-wayland/README.md
- gdk4-wayland/sys/Cargo.toml
- gdk4-x11/Cargo.toml
- gdk4-x11/README.md
- gdk4-x11/sys/Cargo.toml
- gdk4/Cargo.toml
- gdk4/README.md
- gdk4/sys/Cargo.toml
- gsk4/Cargo.toml
- gsk4/README.md
- gsk4/sys/Cargo.toml
- gtk4-macros/Cargo.toml
- gtk4-macros/README.md
- gtk4/Cargo.toml
- gtk4/README.md
- gtk4/sys/Cargo.toml
Corresponds to https://github.com/gtk-rs/gtk-rs-core/pull/434
> Update minimum supported Rust version to 1.57

- gdk4/src/event.rs
- gsk4/src/render_node.rs
- gtk4/src/constant_expression.rs
- gtk4/src/expression.rs
- gtk4/src/object_expression.rs
- gtk4/src/property_expression.rs
> Add is method to fundamental types

- gtk4/src/builders.rs
- gtk4/src/param_spec_expression.rs
> gtk: Add ParamSpecExpressionBuilder

- gdk4/src/keys.rs
There is no way to have proper value checking for Key, so we just assumes it is used
in a correct use case.
Fixes #972
> gdk: Implement Value traits for Key

- .github/workflows/book.yml
> book: Fix CI

- .github/workflows/windows-msvc.yml
> windows CI: build gtk from git

- gtk4-macros/tests/templates.rs
Fixes #992. Just return `None` if another future is still running
> gtk4-macros: Fix re-entrancy panic in async template callback test

- book/book.toml
- book/src/actions.md
- book/src/composite_templates.md
- book/src/css.md
- book/src/gobject_memory_management.md
- book/src/gobject_properties.md
- book/src/gobject_signals.md
- book/src/gobject_subclassing.md
- book/src/gobject_values.md
- book/src/hello_world.md
- book/src/list_widgets.md
- book/src/main_event_loop.md
- book/src/saving_window_state.md
- book/src/settings.md
- book/src/todo_app_1.md
- book/src/todo_app_2.md
- book/src/widgets.md
- book/theme/style.css
Also adds css so the links inherit the color
CC: @ebassi
> book: Link snippets to code examples on github

- .github/workflows/windows-msvc.yml
The current situation let the CI fail quite often
> CI: retry download of pkgconfig-lite

- .github/workflows/image.yml
This is already the case for pushes to master
> CI: run image workflow only if dockerfile has been touched

- Dockerfile
- Get libadwaita from git since the ftp server seems to make problems
- Update comments
- Fix casing
> CI: update Dockerfile

- book/listings/todo_app/2/task_object/mod.rs
- book/listings/todo_app/2/window/imp.rs
- book/listings/todo_app/2/window/mod.rs
- book/listings/todo_app/3/task_object/mod.rs
- book/listings/todo_app/3/window/imp.rs
- book/listings/todo_app/3/window/mod.rs
- book/listings/todo_app/4/task_object/mod.rs
- book/listings/todo_app/4/window/imp.rs
- book/listings/todo_app/4/window/mod.rs
Add `TaskObject::from_task_data`
> book: Improve `TaskData` methods

- gdk4/src/subclass/content_provider.rs
- gtk4/src/subclass/builder_scope.rs
Follow-up of https://github.com/gtk-rs/gtk-rs-core/pull/673.
> Update to last glib version with new IntoGlibPtr trait

- gtk4/src/bitset_iter.rs
- gtk4/src/subclass/widget.rs
Equivalent to https://github.com/gtk-rs/gtk-rs-core/pull/678
> Implement FusedIterator for custom iterators

- book/listings/Cargo.toml
- book/listings/actions/7/window/imp.rs
- book/listings/actions/7/window/mod.rs
- book/listings/todo_app/1/task_object/mod.rs
- book/listings/todo_app/2/main.rs
- book/listings/todo_app/2/org.gtk-rs.Todo2.gschema.xml
- book/listings/todo_app/2/task_object/mod.rs
- book/listings/todo_app/2/utils.rs
- book/listings/todo_app/2/window/imp.rs
- book/listings/todo_app/2/window/mod.rs
- book/listings/todo_app/3/main.rs
- book/listings/todo_app/3/org.gtk-rs.Todo3.gschema.xml
- book/listings/todo_app/3/task_object/mod.rs
- book/listings/todo_app/3/utils.rs
- book/listings/todo_app/3/window/imp.rs
- book/listings/todo_app/3/window/mod.rs
- book/listings/todo_app/4/main.rs
- book/listings/todo_app/4/org.gtk-rs.Todo4.gschema.xml
- book/listings/todo_app/4/task_object/mod.rs
- book/listings/todo_app/4/utils.rs
- book/listings/todo_app/4/window/imp.rs
- book/listings/todo_app/4/window/mod.rs
- book/src/actions.md
- book/src/todo_app_2.md
> Migrate state storing back to json

- book/listings/.cargo/config
- book/listings/Cargo.toml
- book/listings/README.md
- book/listings/xtask/main.rs
> book: Use xtask to install data

- book/src/list_widgets.md
> book: Fixes link in list widgets chapter

- book/src/actions.md
- book/src/g_object_memory_management.md
- book/src/main_event_loop.md
- book/src/saving_window_state.md
- book/src/settings.md
- book/src/todo_2.md
8851339 only changed the listings
> book: Update appid in book

- .github/workflows/windows-msvc.yml
Switch to the official microsoft action for setting up a msvc env
> CI: use msbuild action

- book/listings/Cargo.toml
- book/listings/todo/6/main.rs
- book/listings/todo/6/task_object/imp.rs
- book/listings/todo/6/task_object/mod.rs
- book/listings/todo/6/window/imp.rs
- book/listings/todo/6/window/mod.rs
- book/listings/todo/7/collection_object/imp.rs
- book/listings/todo/7/collection_object/mod.rs
- book/listings/todo/7/main.rs
- book/listings/todo/7/task_object/imp.rs
- book/listings/todo/7/task_object/mod.rs
- book/listings/todo/7/window/imp.rs
- book/listings/todo/7/window/mod.rs
Blocked on new libadwaita-rs release
> book: Replace usage of gtk preludes with adwaita ones

- .github/workflows/CI.yml
- .github/workflows/windows-msvc.yml
- gtk4-macros/Cargo.toml
- gtk4-macros/README.md
- gtk4-macros/src/attribute_parser.rs
- gtk4-macros/src/composite_template_derive.rs
- gtk4/Cargo.toml
- gtk4/README.md
> gtk: Make xml validation optional

- examples/video_player/video_player_window/imp.rs
- gtk4/src/subclass/widget.rs
Yet another helper to get rid of usages of clone! there.
> gtk: Add a WidgetClassSubclassExt::install_action_async

- .github/workflows/CI.yml
> ci: Only run book job if relevant dirs were modified

- examples/custom_editable/custom_editable/imp.rs
- examples/custom_editable/custom_tag/imp.rs
- examples/custom_layout_manager/custom_layout_child/imp.rs
- examples/custom_orientable/custom_orientable/imp.rs
- examples/expressions/metadata/imp.rs
- examples/expressions/note/imp.rs
- examples/list_box_model/list_box_row/imp.rs
- examples/list_box_model/row_data/imp.rs
- examples/rotation_bin/rotation_bin/imp.rs
- examples/squeezer_bin/squeezer_bin/imp.rs
> examples: Use ParamSpec builder pattern

- gdk4/src/event.rs
- gsk4/src/render_node.rs
- gtk4/src/expression.rs
- gtk4/src/param_spec_expression.rs
Depends on https://github.com/gtk-rs/gtk-rs-core/pull/756
> Update for new trait impls in gtk-rs-core

- gsk4/Gir.toml
- gsk4/src/auto/shader_args_builder.rs
- gtk4/Gir.toml
- gtk4/src/auto/snapshot.rs
Depends on https://github.com/gtk-rs/gir/pull/1376
Fixes https://github.com/gtk-rs/gtk4-rs/issues/910
Replaces https://github.com/gtk-rs/gtk4-rs/pull/1019
> gtk: Make use of the new move configuration

- Dockerfile
Part of https://github.com/gtk-rs/gtk-rs-core/issues/484
Depends on an image published from https://github.com/gtk-rs/gtk-rs-core/pull/676
> Base Dockerfile on gtk-rs-core image

- gdk4-win32/Gir.toml
- gdk4-win32/src/auto/win32_display.rs
- gdk4-win32/src/lib.rs
- gdk4-win32/src/win32_display.rs
Not really happy about the result, comments & suggestions welcome!
> gdk-win32: implement Win32Display.add_filter()

- book/src/g_object_subclassing.md
This makes the sentence more cohesive.
> book: Fix typo

- book/src/installation_windows.md
- book/src/libadwaita.md
This PR add Libxml, Librsvg and Gettext which are needed to parse user interface (xml) files as well as to display icons and compile Libadwaita demo.
> Added Libxml, Librsvg, Gettext and Libadwaita demo

- gtk4/src/expression.rs
- gtk4/src/param_spec_expression.rs
@bilelmoussaoui There are probably more places where you can apply the same changes, and the other changes from the glib PR.
> Fix compilation after `Stash` `PhantomData` usage in glib

- gtk4/src/param_spec_expression.rs
> gtk: Make use of Value::from_type_unchecked

- gdk4-x11/src/functions.rs
- gdk4-x11/src/x11_display.rs
- gdk4/src/content_formats_builder.rs
- gdk4/src/display.rs
- gdk4/src/keys.rs
- gdk4/src/rgba.rs
- gsk4/src/transform.rs
- gtk4/src/application.rs
- gtk4/src/builder.rs
- gtk4/src/cell_area.rs
- gtk4/src/constraint_layout.rs
- gtk4/src/dialog.rs
- gtk4/src/entry_buffer.rs
- gtk4/src/file_chooser.rs
- gtk4/src/file_chooser_dialog.rs
- gtk4/src/functions.rs
- gtk4/src/icon_theme.rs
- gtk4/src/message_dialog.rs
- gtk4/src/param_spec_expression.rs
- gtk4/src/snapshot.rs
- gtk4/src/text.rs
> Make use of IntoGStr/IntoStrV

- Dockerfile
blueprint-compiler requires introspection to work
> Enable introspection for gtk

- book/listings/Cargo.toml
- book/listings/list_widgets/2/main.rs
- book/listings/list_widgets/3/main.rs
- book/listings/list_widgets/4/main.rs
- book/listings/list_widgets/5/main.rs
- book/listings/list_widgets/6/main.rs
- book/listings/todo/1/window/mod.rs
- book/listings/todo/2/window/mod.rs
- book/listings/todo/3/window/mod.rs
- book/listings/todo/4/window/mod.rs
- book/listings/todo/5/window/mod.rs
- book/src/project_setup.md
> book: Move listings to feature 4_8

- book/listings/list_widgets/4/main.rs
- book/listings/list_widgets/5/main.rs
- book/listings/list_widgets/6/main.rs
fixed panic in list_widgets_4,5,6 in v4_8.
ref:
https://github.com/gtk-rs/gtk4-rs/blob/6d65d4aa60d575622963958709d13c0419ffa09e/examples/expressions/main.rs#L25-L50
> book: fix panic in list_widgets_4,5,6

- book/listings/Cargo.toml
- book/listings/build.rs
- book/src/composite_templates.md
Ref https://github.com/gtk-rs/gtk-rs-core/pull/917
> book: Adapt to glib-build-tools breaking change

- gdk4/src/rgba.rs
Fixes https://github.com/gtk-rs/gtk4-rs/issues/1314.
> rgba: Add TRANSPARENT const

- book/src/composite_templates.md
> Add a note to the book

- book/src/libadwaita.md
This PR specify Libadwaita latest stable release branch in the book. 
Fix: https://github.com/gtk-rs/gtk4-rs/issues/1355
> Specify libadwaita latest stable release branch in the book. 

- book/src/g_object_subclassing.md
"Unfortunately, nobody found yet a good way to do that" => "Unfortunately, nobody has yet found a good way to do that"
> Improve grammar

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- gdk4/Cargo.toml
- gdk4/README.md
- gdk4/src/gl_texture_builder.rs
- gdk4/src/lib.rs
> Add 'gl' feature to gdk4

- gdk4/src/clipboard.rs
> gdk: Add missing Clipboard::set

- gdk4-wayland/src/lib.rs
- gdk4-wayland/src/wayland_device.rs
- gdk4-wayland/src/wayland_display.rs
- gdk4-wayland/src/wayland_monitor.rs
- gdk4-wayland/src/wayland_seat.rs
- gdk4-wayland/src/wayland_surface.rs
- gdk4-win32/src/lib.rs
- gdk4-win32/src/win32_display.rs
- gdk4-x11/src/functions.rs
- gdk4-x11/src/lib.rs
- gdk4-x11/src/x11_display.rs
- gdk4-x11/src/x11_monitor.rs
- gdk4-x11/src/x11_screen.rs
- gdk4-x11/src/x11_surface.rs
- gdk4/src/content_formats.rs
- gdk4/src/drag_surface.rs
- gdk4/src/lib.rs
- gdk4/src/prelude.rs
- gsk4/src/lib.rs
- gsk4/src/render_node.rs
- gsk4/src/transform.rs
- gtk4/src/expression_watch.rs
- gtk4/src/lib.rs
- gtk4/src/signal_list_item_factory.rs
- gtk4/src/subclass/check_button.rs
- gtk4/src/subclass/combo_box.rs
- gtk4/src/subclass/im_context.rs
- gtk4/src/subclass/mod.rs
- gtk4/src/subclass/widget.rs
Analogous to https://github.com/gtk-rs/gtk3-rs/pull/838 and https://github.com/gtk-rs/gtk-rs-core/pull/1078
The only lines where I was unsure if I had to change them, are all changed in the last commit in this PR. If it was wrong, feel free to revert that commit.
> Untangle docsrs attribute from features

- book/listings/Cargo.toml
- book/listings/css/1/main.rs
- book/listings/css/2/main.rs
- book/listings/css/3/main.rs
- book/listings/css/4/main.rs
- book/listings/css/5/main.rs
- book/listings/css/6/main.rs
- book/listings/css/7/main.rs
- book/listings/css/8/main.rs
- book/listings/css/9/main.rs
- book/listings/todo/1/main.rs
- book/listings/todo/2/main.rs
- book/listings/todo/3/main.rs
- book/listings/todo/4/main.rs
- book/listings/todo/5/main.rs
- book/listings/todo/6/main.rs
- book/listings/todo/7/main.rs
- book/listings/todo/8/main.rs
- book/src/project_setup.md
I only now see that GTK 4.12 is only a couple of days old.
Let's wait at least until Fedora 39 is out.
> Go back to 4_8

- book/src/todo_1.md
> book: Add missing snippet for `new_task`

- book/src/installation_windows.md
> book: Add missing steps for installation in windows

- book/listings/main_event_loop/3/main.rs
- book/listings/main_event_loop/4/main.rs
They should be enough in most situations.
> book: Use bounded channels instead of unbounded

- gdk4-wayland/Gir.toml
- gdk4-wayland/src/auto/wayland_toplevel.rs
- gdk4-wayland/src/lib.rs
- gdk4-wayland/src/wayland_toplevel.rs
- gtk4/Gir.toml
- gtk4/src/auto/file_dialog.rs
- gtk4/src/builder.rs
- gtk4/src/subclass/widget.rs
> Various fixes

- Cargo.toml
- examples/Cargo.toml
- gdk4-wayland/Cargo.toml
- gdk4-wayland/sys/Cargo.toml
- gdk4-win32/Cargo.toml
- gdk4-win32/sys/Cargo.toml
- gdk4-x11/Cargo.toml
- gdk4-x11/sys/Cargo.toml
- gdk4/Cargo.toml
- gdk4/sys/Cargo.toml
- gsk4/Cargo.toml
- gsk4/sys/Cargo.toml
- gtk4-macros/Cargo.toml
- gtk4/Cargo.toml
- gtk4/sys/Cargo.toml
Sadly we can't use the same mechanism for ffi crates as we rename the packages in the Cargo.toml making it meh :(
> Use cargo workspace features

- book/listings/Cargo.lock
- book/listings/Cargo.toml
- book/listings/g_object_signals/2/custom_button/imp.rs
- book/listings/main_event_loop/9/main.rs
- book/src/g_object_signals.md
- book/src/main_event_loop.md
@bilelmoussaoui not sure if there's a good way to initialize tokio without the once_cell crate at the moment
> book: Less usage of once_cell

- gdk4/src/subclass/content_provider.rs
- gtk4/src/subclass/builder_scope.rs
Fixes https://github.com/gtk-rs/gtk4-rs/issues/1671
> Correctly handle `NULL` `GError**` out parameters

- book/src/todo_1.md
Text talksa bout Window::model when the code actually adds Window::tasks
> Fix typo in todo_1.md

- examples/glium_gl_area/glium_gl_area/imp.rs
Fixes https://github.com/gtk-rs/gtk4-rs/issues/1731
> examples: Support GL >= 3.1 and GLES >= 3.0 in the glium example

- examples/custom_orientable/custom_orientable/imp.rs
We need to both override the property and add the derive_properties to the ObjectImpl
Close #1753
> custom_orientable: Fix interface property override

- examples/squeezer_bin/main.rs
- examples/squeezer_bin/squeezer_bin/imp.rs
- examples/squeezer_bin/squeezer_bin/mod.rs
> examples/squeezer_bin: Mark properties as writable

- book/src/introduction.md
- book/src/libadwaita.md
> book: Add link to Chinese translation

- gtk4/Cargo.toml
- gtk4/README.md
Addresses #2030. Hope I did it the right way!
> gtk: add gnome_48 features

- examples/README.md
> Fix broken link to the "ListBox: StringList with Sorter" example.
